[project]
name = "gan-from-scratch-pytorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.30.1",
    "torch>=2.7.1",
    "torchvision>=0.22.1",
]
